import Head from "next/head";
import Category from "@/components/Category";
import SellProducts from "@/components/SellProducts";
import Hero from "@/components/Hero";
import ListingCard from "@/components/ListingCard";
import "twin.macro";
import zayyan from "../../public/images/zayyan.png";
import decor from "../../public/images/just_decor.png";
import jameel from "../../public/images/jameel.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Muslim Space</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero />
        <Category />
        <section tw="p-5">
          <h2 tw="text-center text-[#271C0C] font-semibold text-5xl mb-3 font-playfair">
            Featured Products
          </h2>
          <div tw="flex flex-wrap">
            <ListingCard productImg={jameel} />
            <ListingCard productImg={zayyan} />
            <ListingCard productImag={decor} />
            <ListingCard productImg={jameel} />
            <ListingCard productImg={zayyan} />
            <ListingCard productImag={decor} />
          </div>
        </section>
        <SellProducts />
      </div>
    </>
  );
}
